runtime: nodejs20 # Specify the Node.js runtime version
env: standard # Use the standard environment
instance_class: F1 # Define the instance class (F1 is the smallest available)

automatic_scaling:
  min_idle_instances: 0 # Minimum number of idle instances
  max_idle_instances: automatic # Maximum number of idle instances (automatic scaling)
  min_pending_latency: automatic # Minimum time a request waits in the queue
  max_pending_latency: automatic # Maximum time a request waits in the queue

env_variables:
  MYSQL_HOST: 'aws.connect.psdb.cloud'
  MYSQL_USER: 'tsi0flj239gqhmkl2pky'
  MYSQL_PASSWORD: 'pscale_pw_6wQj1BmnMaJdwqMnnJ7rN1mbIsX65Mfj3mTneJOOOUl'
  MYSQL_DATABASE: 'bloggy'



